[features]
seeds = false
[programs.localnet]
useless_switch = "8QB7HjktK1sbnnMnXBuMxo1BQpT5gcAUpcvhEmLEk9ED"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jake503/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
